
[window]
dynamic_title = false
title = "Alacritty"
opacity = 0.9

[font]
size = 12

[font.normal]
family = "HackGen35ConsoleNF"

[terminal.shell]
program = "/bin/zsh"
args = [
  "-l",
  "-c",
  "tmux a -t main || tmux new -s main",
]

[keyboard]
bindings = [
{ key = "¥", chars = "\\"}
]

[general]
# theme
import = [
    "~/dotfiles/.config/alacritty/themes/themes/kanagawa_wave.toml"
    ]

[terminal]
