# theme
import = [
    "~/dotfiles/.config/alacritty/themes/themes/gruvbox_dark.toml"
    ]

[window]
dynamic_title = false
title = "Alacritty"
opacity = 0.9

[font]
size = 16

[font.normal]
family = "HackGen35 Console NF"

